# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .Program import Program

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class LibraSignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 804

    def __init__(
        self,
        address_n: List[int] = None,
        sender_account: bytes = None,
        sequence_number: int = None,
        payload: Program = None,
        max_gas_amount: int = None,
        gas_unit_price: int = None,
        expiration_time: int = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.sender_account = sender_account
        self.sequence_number = sequence_number
        self.payload = payload
        self.max_gas_amount = max_gas_amount
        self.gas_unit_price = gas_unit_price
        self.expiration_time = expiration_time

    @classmethod
    def get_fields(cls):
        return {
            1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            2: ('sender_account', p.BytesType, 0),
            3: ('sequence_number', p.UVarintType, 0),
            4: ('payload', Program, 0),
            5: ('max_gas_amount', p.UVarintType, 0),
            6: ('gas_unit_price', p.UVarintType, 0),
            7: ('expiration_time', p.UVarintType, 0),
        }
