# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class LibraSignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 805

    def __init__(
        self,
        raw_txn_bytes: bytes = None,
        sender_public_key: bytes = None,
        signature: bytes = None,
    ) -> None:
        self.raw_txn_bytes = raw_txn_bytes
        self.sender_public_key = sender_public_key
        self.signature = signature

    @classmethod
    def get_fields(cls):
        return {
            1: ('raw_txn_bytes', p.BytesType, 0),
            2: ('sender_public_key', p.BytesType, 0),
            3: ('signature', p.BytesType, 0),
        }
