# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class PolkadotBalanceTransfer(p.MessageType):

    def __init__(
        self,
        module_index: int = None,
        call_index: int = None,
        destination: bytes = None,
        value: int = None,
    ) -> None:
        self.module_index = module_index
        self.call_index = call_index
        self.destination = destination
        self.value = value

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('module_index', p.UVarintType, 0),
            2: ('call_index', p.UVarintType, 0),
            3: ('destination', p.BytesType, 0),
            4: ('value', p.UVarintType, 0),
        }
