# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .PolkadotBalanceTransfer import PolkadotBalanceTransfer

if __debug__:
    try:
        from typing import Dict, List, Optional
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class PolkadotSignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 804

    def __init__(
        self,
        address_n: List[int] = None,
        era: bytes = None,
        nonce: int = None,
        tip: int = None,
        genesis_hash: bytes = None,
        block_hash: bytes = None,
        transfer: PolkadotBalanceTransfer = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.era = era
        self.nonce = nonce
        self.tip = tip
        self.genesis_hash = genesis_hash
        self.block_hash = block_hash
        self.transfer = transfer

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            2: ('era', p.BytesType, 0),
            3: ('nonce', p.UVarintType, 0),
            4: ('tip', p.UVarintType, 0),
            5: ('genesis_hash', p.BytesType, 0),
            6: ('block_hash', p.BytesType, 0),
            7: ('transfer', PolkadotBalanceTransfer, 0),
        }
