# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .TransactionArguments import TransactionArguments

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class Program(p.MessageType):

    def __init__(
        self,
        code: bytes = None,
        args: List[TransactionArguments] = None,
        modules: List[bytes] = None,
    ) -> None:
        self.code = code
        self.args = args if args is not None else []
        self.modules = modules if modules is not None else []

    @classmethod
    def get_fields(cls):
        return {
            1: ('code', p.BytesType, 0),
            2: ('args', TransactionArguments, p.FLAG_REPEATED),
            3: ('modules', p.BytesType, p.FLAG_REPEATED),
        }
