# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class TransactionArguments(p.MessageType):

    def __init__(
        self,
        type: int = None,
        data: bytes = None,
    ) -> None:
        self.type = type
        self.data = data

    @classmethod
    def get_fields(cls):
        return {
            1: ('type', p.UVarintType, 0),
            2: ('data', p.BytesType, 0),
        }
