# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class WriteSet(p.MessageType):

    def __init__(
        self,
        blob: str = None,
    ) -> None:
        self.blob = blob

    @classmethod
    def get_fields(cls):
        return {
            1: ('blob', p.UnicodeType, 0),
        }
