# Automatically generated by pb2py
# fmt: off
import protobuf as p


class TezosControlStaking(p.MessageType):
    MESSAGE_WIRE_TYPE = 158

    def __init__(
        self,
        staking: bool = None,
    ) -> None:
        self.staking = staking

    @classmethod
    def get_fields(cls):
        return {
            1: ('staking', p.BoolType, 0),
        }
