# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class AeternitySignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 804

    def __init__(
        self,
        address_n: List[int] = None,
        network: int = None,
        vsn: int = None,
        sender_id: str = None,
        recipient_id: str = None,
        amount: int = None,
        fee: int = None,
        ttl: int = None,
        nonce: int = None,
        payload: str = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.network = network
        self.vsn = vsn
        self.sender_id = sender_id
        self.recipient_id = recipient_id
        self.amount = amount
        self.fee = fee
        self.ttl = ttl
        self.nonce = nonce
        self.payload = payload

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            2: ('network', p.UVarintType, 0),
            3: ('vsn', p.UVarintType, 0),
            4: ('sender_id', p.UnicodeType, 0),
            5: ('recipient_id', p.UnicodeType, 0),
            6: ('amount', p.UVarintType, 0),
            7: ('fee', p.UVarintType, 0),
            8: ('ttl', p.UVarintType, 0),
            9: ('nonce', p.UVarintType, 0),
            10: ('payload', p.UnicodeType, 0),
        }
