# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class CosmosPublicKey(p.MessageType):
    MESSAGE_WIRE_TYPE = 803

    def __init__(
        self,
        public_key: str = None,
        public_key_hex: str = None,
    ) -> None:
        self.public_key = public_key
        self.public_key_hex = public_key_hex

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('public_key', p.UnicodeType, 0),
            2: ('public_key_hex', p.UnicodeType, 0),
        }
