# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class PolkadotSignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 805

    def __init__(
        self,
        signature: str = None,
        encoded_value: str = None,
        encoded_nonce: str = None,
    ) -> None:
        self.signature = signature
        self.encoded_value = encoded_value
        self.encoded_nonce = encoded_nonce

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('signature', p.UnicodeType, 0),
            2: ('encoded_value', p.UnicodeType, 0),
            3: ('encoded_nonce', p.UnicodeType, 0),
        }
