# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class TezosManagerTransfer(p.MessageType):

    def __init__(
        self,
        destination: bytes = None,
        amount: int = None,
    ) -> None:
        self.destination = destination
        self.amount = amount

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('destination', p.BytesType, 0),
            2: ('amount', p.UVarintType, 0),
        }
