# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .TezosManagerSmartContractTransfer import TezosManagerSmartContractTransfer

if __debug__:
    try:
        from typing import Dict, List, Optional
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class TezosManagerSmartContractParams(p.MessageType):

    def __init__(
        self,
        set_delegate: bytes = None,
        cancel_delegate: bool = None,
        transfer: TezosManagerSmartContractTransfer = None,
    ) -> None:
        self.set_delegate = set_delegate
        self.cancel_delegate = cancel_delegate
        self.transfer = transfer

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('set_delegate', p.BytesType, 0),
            2: ('cancel_delegate', p.BoolType, 0),
            3: ('transfer', TezosManagerSmartContractTransfer, 0),
        }
